#include <string>

#ifndef __CREDITS_H__230984729380740298374092837423__
#define __CREDITS_H__230984729380740298374092837423__

namespace klib
{
	static const std::string namesSpecialThanks[] =
	{	"-- Loosely based on homework code and idea by --"	
	,	"Nethrim"					
	,	""							
	,	"-- Programming --"			
	,	"asm128"						
	,	""							
	,	"-- Graphics --"			
	,	"asm128"						
	,	""							
	,	"-- Design --"			
	,	"asm128"						
	,	"Gorby"						
	,	""							
	,	"-- Testers --"				
	,	"Gorby"						
	,	"Nethrim"					
	,	""							
	,	"-- Sound Effects --"		
	,	"Jim Rogers"	//(Shotgun)"						
	,	"Mark DiAngelo"	//(Intro wind, explosion)"						
	,	"Daniel Simon"	//(Grenade Launcher)"						
	,	"Mike Koenig"	//(Grenade, gun)"						
	,	"Marvin"		//(Gun Shot)"						
	,	"battlestar10"	//(M1 Garand)"						
	,	"Kibblesbob"	//(M1 Garand)"						
	,	""							
	,	"-- Hardware contributions --"		
	,	"asm128"						
	,	"Hern\xA0n Parra"						
	,	""							
	,	"-- Everything else --"		
	,	"asm128"						
	,	""							
	//,	"-- Special Thanks to --"	
	//,	"Nethrim"	
	//,	"Gorby"		
	//,	"Andrew"	
	//,	"James"		
	//,	"Suelika"	
	//,	"Paul"		
	//,	"Bill"		
	//,	"Matt"		
	//,	"Robert"	
	//,	"Riva"		
	//,	"Pia"		
	//,	"David"		
	//,	"Stuart"	
	//,	"Nhi"		
	//,	"Andy"		
	//,	"Esteban"	
	//,	"Chi-Wei"	
	//,	"Michael"	
	//,	"Serguei"	
	//,	"Henry"		
	//,	"Kirk"		
	//,	"Gabriela"	
	//,	"Jeff"		
	//,	"Marc"		
	//,	"Jose"		
	//,	"Jose"		
	//,	"Zach"		
	//,	"Anson"		
	//,	"Vitaliy"	
	//,	"Emily"		
	//,	"Cara"		
	//,	"Brent"		
	//,	"Fredrik"	
	//,	"Adan"		
	//,	"Ted"		
	//,	"Terran"	
	//,	"Nicolas"	
	//,	"Nicolas"	
	//,	"Martin"	
	//,	"Mauro"		
	//,	"Luis"		
	//,	"Carlos"	
	//,	"Atul"		
	//,	""									
	//,	""									
	//,	"Have a nice weekend!"				
	//,	""									
	//,	""									
	,	"Press ESC to return to main menu."	
	};
}

#endif // __CREDITS_H__230984729380740298374092837423__
